version: '3.8'
services:
  db:
    image: mysql:8.0 #imagen oficial de mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    command: 
      --character-set-server=utf8mb4 
      --collation-server=utf8mb4_unicode_ci
      --max_allowed_packet=100M #en caso de que en MySQL este limitado
    ports:
      - "${DB_PORT}:3307"
    volumes:
      - ./evall_mysql_data:/var/lib/mysql #esto no lo he subido
      - ./db:/docker-entrypoint-initdb.d
    restart: always
  backend:
    build: ./backend
    ports:
      - "3001:3000"
    environment:
      DB_HOST: ${DB_HOST}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
    volumes:
      - ./backend:/myapp
      - /myapp/node_modules
    depends_on:
      - db
    restart: always
  frontend:
    build: ./frontend
    ports:
      - "5001:80"
    environment:
      VITE_API_URL: "http://localhost:3001" #liga al backend para las peticiones
    depends_on:
      - backend
    restart: always
volumes:
  mysql_data: 